version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: campusreach-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: campusreach
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d campusreach"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
