name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    env:
      CI: true
      # Avoid failing builds when env validation is strict
      SKIP_ENV_VALIDATION: '1'
      NEXTAUTH_URL: http://localhost:3000
      AUTH_SECRET: test-secret
      DATABASE_URL: postgresql://user:pass@localhost:5432/db?schema=public
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
          run_install: false

      - name: pnpm version
        run: pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm exec prisma generate

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Build
        run: pnpm build
